ACTIVE_ENUM = {0: "inactive", 1: "active"}

STR_TO_INT = {
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "ten": "10",
    "eleven": "11",
    "twelve": "12",
    "thirteen": "13",
    "fourteen": "14",
    "fifteen": "15",
    "sixteen": "16",
    "seventeen": "17",
    "eighteen": "18",
    "nineteen": "19",
    "twenty": "20",
    "twenty-one": "21",
    "twenty one": "21",
    "twenty-two": "22",
    "twenty two": "22",
    "twenty-three": "23",
    "twenty three": "23",
    "twenty-four": "24",
    "twenty four": "24",
}

TIME_IN_MINUTES = {
    "hour": 60,
    "day": 1400,
    "week": 10080,
    "month": 43800,
    "year": 525600,
}
